# Generated by Django 4.0.1 on 2022-01-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=123, upload_to='upload/'),
            preserve_default=False,
        ),
    ]
